version: '4'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  
    networks:
      - app_network
    depends_on:
      - myits
      - api-myits

networks:
  app_network:
    external: true 
